apiVersion: v1
kind: Secret
metadata:
  name: {{ include "permission-manager.fullname" . }} 
  labels:
    {{- include "permission-manager.labels" . | nindent 4 }}
type: Opaque
stringData:
  PORT: "4000" # port where server is exposed
  CLUSTER_NAME: {{ .Values.config.clusterName | quote }}
  CONTROL_PLANE_ADDRESS: {{ default .Values.config.controlePlaneAddress .Values.config.controlPlaneAddress | quote }}
  BASIC_AUTH_PASSWORD: {{ .Values.config.basicAuthPassword | quote }}
